import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {business as b,wa,generalMessage,packMessage} from '../src/data.mjs';
const revision=createHash('sha256').update(fs.readFileSync('src/beatriz.css')).update(fs.readFileSync('src/beatriz.js')).update(fs.readFileSync('src/data.mjs')).update(fs.readFileSync('docs/assets/photos/beatriz-logo.webp')).digest('hex').slice(0,12);
const escape = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const icon = (name,cls='') => `<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
const icons = `<svg class="icon-sprite" xmlns="http://www.w3.org/2000/svg"><defs>
<symbol id="i-arrow" viewBox="0 0 24 24"><path d="M5 12h14m-6-6 6 6-6 6"/></symbol>
<symbol id="i-check" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></symbol>
<symbol id="i-shirt" viewBox="0 0 24 24"><path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c0 4-8 4-8 0Z"/></symbol>
<symbol id="i-clock" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></symbol>
<symbol id="i-phone" viewBox="0 0 24 24"><path d="m5 3 4 4-2 3c2 3 4 5 7 7l3-2 4 4c-1 3-4 3-6 2C8 18 4 14 2 7 1 5 2 3 5 3Z"/></symbol>
<symbol id="i-wa" viewBox="0 0 24 24"><path d="M21 11.5A9 9 0 0 1 7 19L2 21l1.5-5A9 9 0 1 1 21 11.5Z"/><path d="m8 7 2 2-1 2 3 3 2-1 2 2c-1 3-7 0-9-4-1-2 0-3 1-4Z"/></symbol>
<symbol id="i-spark" viewBox="0 0 24 24"><path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/></symbol>
<symbol id="i-plus" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></symbol>
<symbol id="i-play" viewBox="0 0 24 24"><path d="m8 5 12 7-12 7Z"/></symbol>
</defs></svg>`;
const brand=(prefix='')=>`<a class="brand" href="${prefix||'#inicio'}" aria-label="Engomadoria Beatriz — início"><img src="${prefix}assets/photos/beatriz-logo.webp?v=${revision}" width="1536" height="630" alt="Engomadoria Beatriz Lavandaria"></a>`;
const schema={ '@context':'https://schema.org','@graph':[
 {'@type':'LocalBusiness','@id':b.url+'#negocio',name:b.fullName,url:b.url,telephone:b.phone,image:b.url+'assets/photos/beatriz-editorial.webp',openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens:'10:00',closes:'12:30'},{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens:'14:00',closes:'19:00'},{'@type':'OpeningHoursSpecification',dayOfWeek:'Saturday',opens:'10:00',closes:'15:00'}],hasOfferCatalog:{'@type':'OfferCatalog',name:'Packs de engomadoria e limpeza têxtil',itemListElement:[...b.packs.map(p=>({'@type':'Offer',price:String(p.price),priceCurrency:'EUR',itemOffered:{'@type':'Service',name:`Pack de engomadoria — ${p.pieces} peças`}})),{'@type':'Offer',price:'2',priceCurrency:'EUR',itemOffered:{'@type':'Service',name:'Lavandaria para Alojamento Local — roupa branca, por kg'}}]}},
 {'@type':'WebSite','@id':b.url+'#website',url:b.url,name:b.name,inLanguage:'pt-PT'},
 {'@type':'FAQPage','@id':b.url+'#faq',mainEntity:b.faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}
]};
const head=(title,description,route='')=>`<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#fff4f7"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${b.url+route}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_PT"><meta property="og:site_name" content="${b.name}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${b.url+route}"><meta property="og:image" content="${b.url}assets/photos/beatriz-editorial.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${route?'../':''}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${route?'../':''}assets/beatriz.css?v=${revision}"><script type="application/ld+json">${JSON.stringify(schema)}</script>${route?'':`<link rel="preload" href="assets/photos/beatriz-editorial.webp" as="image" fetchpriority="high"><script src="assets/beatriz.js?v=${revision}" defer></script>`}</head>`;
const footer=(prefix='')=>`<footer class="footer"><div class="wrap footer-top">${brand(prefix)}<p>Roupa cuidada.<br>Mais tempo para si.</p><a class="footer-phone" href="tel:${b.phone}">${b.displayPhone}</a></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Engomadoria Beatriz Lavandaria</span><nav aria-label="Informação"><a href="${prefix}precos/">Preços</a><a href="${prefix}perguntas-frequentes/">Perguntas frequentes</a><a href="${prefix}contactos/">Contactos</a></nav></div></footer>`;
const faqs=b.faq.map(([q,a])=>`<details><summary>${q}${icon('plus')}</summary><p>${a}</p></details>`).join('');
const logoPieces=[{x:0,y:0,w:460,h:630},...[[460,0,1076,220,11],[460,220,1076,236,7],[460,456,1076,174,10]].flatMap(([x,y,w,h,n])=>Array.from({length:n},(_,i)=>({x:x+i*w/n,y,w:w/n,h})))];
const assembledLogo=`<svg class="logo-assembly" viewBox="0 0 1536 630" aria-hidden="true"><defs>${logoPieces.map((p,i)=>`<clipPath id="logo-piece-${i}"><rect x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}"/></clipPath>`).join('')}</defs>${logoPieces.map((p,i)=>`<g class="logo-piece" style="--delay:${(i===0?0:i*.025).toFixed(3)}s;--dx:${(i%2?1:-1)*(8+(i%5)*2)}px;--dy:${(i%3-1)*8}px;--turn:${(i%2?1:-1)*0}deg;transform-origin:${p.x+p.w/2}px ${p.y+p.h/2}px"><image href="assets/photos/beatriz-logo.webp?v=${revision}" width="1536" height="630" clip-path="url(#logo-piece-${i})"/></g>`).join('')}</svg>`;
const html=head('Engomadoria Beatriz | Packs de engomadoria e pedidos por WhatsApp','Conheça os packs de engomadoria da Beatriz, de 20 a 100 peças. Roupa branca para Alojamento Local a 2 €/kg e limpeza têxtil. Pedidos por WhatsApp.')+`<body>${icons}<a class="skip" href="#conteudo">Saltar para o conteúdo</a>
<div class="intro intro-flow" role="dialog" aria-modal="true" aria-label="Bem-vindo à Engomadoria Beatriz"><div class="intro-stage"><video id="intro-video" muted playsinline preload="auto" poster="assets/photos/beatriz-flow-poster.webp" aria-hidden="true"><source src="assets/beatriz-intro-flow.mp4" type="video/mp4"></video><div class="intro-signature">${assembledLogo}</div><button class="intro-enter" id="intro-enter" type="button" hidden>ENTRAR</button><p class="intro-enter-hint" hidden>O seu cuidado começa aqui.</p></div><button class="intro-skip" id="intro-skip" type="button">Entrar já <span aria-hidden="true">↗</span></button></div>
<div class="announcement"><span>Um cuidado a menos no seu dia.</span><a href="${wa(generalMessage)}">Fale directamente com a Beatriz ${icon('wa')}</a></div>
<header class="header" id="inicio"><div class="wrap header-inner">${brand()}<nav class="desktop-nav" aria-label="Principal"><a href="#packs">Packs</a><a href="#al">Alojamento Local</a><a href="#servicos">Serviços</a><a href="#contacto">Contactos</a></nav><a class="button button-dark header-cta" href="${wa(generalMessage)}">Pedir no WhatsApp ${icon('wa')}</a><button class="menu-toggle" aria-controls="mobile-menu" aria-expanded="false" aria-label="Abrir menu"><span></span><span></span></button></div><nav id="mobile-menu" class="mobile-menu" aria-label="Navegação móvel" hidden><a href="#packs">Packs de engomadoria</a><a href="#al">Alojamento Local</a><a href="#servicos">Outros serviços</a><a href="#contacto">Contactos e horário</a></nav></header>
<main id="conteudo">
<section class="hero" aria-labelledby="hero-title"><div class="hero-image"><img src="assets/photos/beatriz-editorial.webp" width="1536" height="1024" alt="Camisas cuidadas em tons claros e roupa dobrada" fetchpriority="high"></div><div class="wrap hero-inner"><div class="hero-copy"><p class="eyebrow">ENGOMADORIA & LAVANDARIA</p><h1 id="hero-title">A sua roupa.<br><em>O nosso cuidado.</em></h1><p class="hero-description">Tire a roupa da lista de tarefas.<br>Escolha o seu pack e fale com a Beatriz.</p><div class="hero-actions"><a class="button button-pink" href="#packs">Encontrar o meu pack ${icon('arrow')}</a><a class="text-link" href="${wa(generalMessage)}">Só tenho uma dúvida ${icon('wa')}</a></div><div class="hero-note">${icon('check')} Packs de 20 a 100 peças <span>·</span> Contacto directo</div></div><div class="hero-seal"><span>Um toque</span><strong>Beatriz</strong><span>em cada peça</span></div><span class="hero-caption">Vapor. Tempo. Cuidado.</span></div></section>
<div class="care-strip"><div class="wrap"><span>${icon('shirt')} Packs para a sua rotina</span><span>${icon('spark')} Limpeza têxtil</span><span>${icon('wa')} Pedidos por WhatsApp</span></div></div>
<section class="packs section wrap" id="packs" aria-labelledby="packs-title"><div class="section-heading"><div><p class="eyebrow">01 / A SUA ROUPA, SEM COMPLICAÇÕES</p><h2 id="packs-title">Menos roupa por tratar.<br><em>Mais tempo para si.</em></h2></div><p>De uma pequena pilha à roupa de toda a família. Escolha a quantidade que faz sentido para si.</p></div><div class="pack-options" role="group" aria-label="Escolher pack de engomadoria">${b.packs.map((p,i)=>`<button class="pack-option ${i===2?'selected':''}" type="button" data-pieces="${p.pieces}" data-price="${p.price}" aria-pressed="${i===2}">${i===2?'<span class="pack-tag">PARA A ROTINA</span>':''}<span class="pack-count">${p.pieces}<small>peças</small></span><span class="pack-price">${p.price}<small> €</small></span><span class="pack-unit">${(Math.round(p.price*100/p.pieces)/100).toFixed(2).replace('.',',')} € / peça</span><span class="pack-check">${icon('check')}</span></button>`).join('')}</div>
<div class="pack-order"><div><span class="eyebrow">O SEU PACK</span><h3 id="pack-summary">60 peças · 49 €</h3><p>O pedido segue preparado. A Beatriz confirma as condições e o prazo consigo.</p></div><a class="button button-dark" id="pack-whatsapp" href="${wa(packMessage(b.packs[2]))}">Pedir este pack ${icon('wa')}</a></div><p class="pack-disclaimer">Valores por pack. Confirme as peças abrangidas e as condições antes de entregar a roupa.</p><p id="pack-status" class="sr-only" aria-live="polite"></p><noscript><div class="nojs-packs">${b.packs.map(p=>`<a href="${wa(packMessage(p))}">Pedir ${p.pieces} peças — ${p.price} €</a>`).join('')}</div></noscript>
</section>
<section class="story section" id="galeria"><div class="wrap story-grid"><div class="story-copy"><img class="brand-reminder" src="assets/photos/beatriz-logo.webp?v=${revision}" width="1536" height="630" alt="Engomadoria Beatriz Lavandaria" loading="lazy"><p class="eyebrow">O CUIDADO ESTÁ NOS DETALHES</p><h2>Aquela sensação<br>de ter tudo<br><em>em ordem.</em></h2><p>Uma camisa pronta a vestir. A roupa da semana arrumada. Pequenos cuidados que deixam o dia mais leve.</p><a class="text-link" href="${wa(generalMessage)}">Conte-nos o que precisa ${icon('arrow')}</a></div><div class="film"><video id="care-video" muted loop playsinline preload="none" poster="assets/photos/beatriz-editorial.webp" aria-label="Filme de apresentação da Engomadoria Beatriz"><source src="assets/beatriz-care.mp4" type="video/mp4"></video><div class="film-caption"><span>BEATRIZ / O FILME</span><button id="video-toggle" type="button" aria-label="Reproduzir vídeo de apresentação">${icon('play')} <span>Ver o cuidado</span></button></div><p id="video-status" class="sr-only" aria-live="polite"></p></div></div></section>
<section class="al section" id="al"><div class="wrap al-grid"><div class="al-image"><img src="assets/photos/linen.webp" alt="Toalhas brancas dobradas para acolher hóspedes" width="1000" height="667" loading="lazy"><span>ROUPA BRANCA / ALOJAMENTO LOCAL</span></div><div class="al-copy"><p class="eyebrow">02 / PARA QUEM RECEBE</p><h2>O cuidado que<br>os seus hóspedes<br><em>também sentem.</em></h2><p>Lavandaria para a roupa branca do seu Alojamento Local. Um contacto directo para confirmar quantidades, condições e datas.</p><div class="al-rate"><strong>2<span> €/kg</span></strong><span>Roupa branca<br>Alojamento Local</span></div><a class="button button-pink" href="#pedido" data-intent="al">Preparar pedido de AL ${icon('arrow')}</a></div></div></section>
<section class="services section wrap" id="servicos"><div class="section-heading"><div><p class="eyebrow">03 / MAIS DO QUE ENGOMAR</p><h2>Há mais roupa<br><em>que merece cuidado.</em></h2></div><p>Dos tecidos de casa às peças especiais. Consulte a disponibilidade e peça um orçamento.</p></div><div class="services-list">${b.services.map((name,i)=>`<a href="#pedido" class="service-row" data-intent="${escape(name)}"><span class="service-number">0${i+1}</span><h3>${name}</h3><span class="service-action">Consultar ${icon('arrow')}</span></a>`).join('')}</div><p class="service-footnote">Precisa de outro serviço? <a href="${wa('Olá, Beatriz! Gostaria de saber se fazem o seguinte serviço: ')}">Pergunte à Beatriz.</a></p></section>
<section class="request section" id="pedido"><div class="wrap request-grid"><div><p class="eyebrow">VAMOS TRATAR DISSO?</p><h2>O primeiro passo<br>é só uma<br><em>mensagem.</em></h2><p>Escolha o serviço. Acrescente o que precisa.<br>O seu pedido fica pronto para o WhatsApp.</p><p class="request-note">${icon('check')} Sem conta. Sem pagamento no site.</p></div><form class="request-card" id="request-form"><label for="service-select">De que precisa?</label><select id="service-select" name="service"><option value="pack">Pack de engomadoria</option><option value="al">Roupa branca · Alojamento Local</option>${b.services.map(n=>`<option value="${escape(n)}">${n}</option>`).join('')}<option value="outro">Outro serviço / uma dúvida</option></select><div id="request-pack-field"><label for="request-pack">Escolha o seu pack</label><select id="request-pack" name="pack">${b.packs.map(p=>`<option value="${p.pieces}" ${p.pieces===60?'selected':''}>${p.pieces} peças — ${p.price} €</option>`).join('')}</select></div><div id="request-al-field" hidden><label for="request-quantity">Quantidade aproximada (kg, opcional)</label><input id="request-quantity" name="quantity" type="number" min="0.5" max="10000" step="0.5" inputmode="decimal" placeholder="Ex.: 15"></div><label for="request-notes">Quer acrescentar alguma coisa? <span>(opcional)</span></label><textarea id="request-notes" name="notes" rows="2" maxlength="500" placeholder="A data pretendida, o tipo de roupa ou uma dúvida…"></textarea><div class="message-preview"><span>A SUA MENSAGEM</span><p id="message-preview">${packMessage(b.packs[2])}</p></div><a class="button button-pink request-submit" id="request-whatsapp" href="${wa(packMessage(b.packs[2]))}">Abrir o meu pedido no WhatsApp ${icon('wa')}</a><p class="form-note">Só envia a mensagem quando confirmar no WhatsApp.</p><noscript><p><a href="${wa(generalMessage)}">Contactar a Beatriz directamente no WhatsApp</a></p></noscript></form></div></section>
<section class="faq section wrap" id="faq"><div><p class="eyebrow">ANTES DE FALAR CONNOSCO</p><h2>As suas dúvidas.<br><em>Sem rodeios.</em></h2><a class="text-link" href="${wa('Olá, Beatriz! Tenho uma dúvida sobre os vossos serviços.')}">Perguntar à Beatriz ${icon('wa')}</a></div><div class="faq-list">${faqs}</div></section>
<section class="contact section" id="contacto"><div class="wrap contact-grid"><div><p class="eyebrow">O SEU CONTACTO DIRECTO</p><h2>Fale com<br><em>a Beatriz.</em></h2><a class="contact-phone" href="tel:${b.phone}">${b.displayPhone}</a><div class="contact-actions"><a class="button button-pink" href="${wa(generalMessage)}">WhatsApp ${icon('wa')}</a><a class="button button-outline" href="tel:${b.phone}">Telefonar ${icon('phone')}</a></div></div><div class="hours"><h3>${icon('clock')} Quando nos encontra</h3><div><span>Segunda a sexta-feira</span><b>10:00–12:30<br>14:00–19:00</b></div><div><span>Sábado</span><b>10:00–15:00</b></div><div><span>Domingos e feriados</span><b>Encerrado</b></div><a class="text-link" href="${wa('Olá, Beatriz! Pode indicar-me a morada e como chegar para entregar a roupa?')}">Pedir indicações de chegada ${icon('arrow')}</a></div></div></section>
</main>${footer()}<div class="mobile-dock"><a href="#packs">${icon('shirt')}<span>Ver packs</span></a><a href="${wa(generalMessage)}">${icon('wa')}<span>Falar com a Beatriz</span></a></div></body></html>`;
fs.writeFileSync('docs/index.html',html);
const subpages=[
 ['precos/','Preços e packs de engomadoria | Engomadoria Beatriz','Packs de 20, 40, 60, 80 e 100 peças. Compare os preços da Engomadoria Beatriz e peça o seu pack por WhatsApp.',`<p class="eyebrow">PACKS DE ENGOMADORIA</p><h1>Um pack para<br><em>a sua rotina.</em></h1><p>Escolha a quantidade de roupa e confirme as condições directamente com a Beatriz.</p><div class="sub-prices">${b.packs.map(p=>`<a href="${wa(packMessage(p))}"><strong>${p.pieces} peças</strong><b>${p.price} €</b><span>Pedir no WhatsApp ${icon('wa')}</span></a>`).join('')}</div><p>Confirme as peças abrangidas, a disponibilidade e o prazo antes de entregar a roupa.</p><h2>Roupa branca de Alojamento Local</h2><p>Lavandaria para Alojamento Local a <strong>2 €/kg</strong>.</p><a class="button button-pink" href="${wa('Olá, Beatriz! Gostaria de informações sobre roupa branca de Alojamento Local a 2 €/kg.')}">Consultar condições ${icon('wa')}</a>`],
 ['perguntas-frequentes/','Perguntas frequentes | Engomadoria Beatriz','Respostas sobre packs de engomadoria, roupa branca para Alojamento Local, limpeza têxtil, horário e pedidos por WhatsApp.',`<p class="eyebrow">INFORMAÇÃO DIRECTA</p><h1>As suas dúvidas.<br><em>Sem rodeios.</em></h1><div class="faq-list">${faqs}</div>`],
 ['contactos/','Contacto e horário | Engomadoria Beatriz','Contacte a Engomadoria Beatriz pelo 923 250 845, por telefone ou WhatsApp. Consulte o horário e peça indicações para entregar a roupa.',`<p class="eyebrow">ENGOMADORIA BEATRIZ</p><h1>Fale com<br><em>a Beatriz.</em></h1><p class="contact-phone"><a href="tel:${b.phone}">${b.displayPhone}</a></p><a class="button button-pink" href="${wa(generalMessage)}">Abrir WhatsApp ${icon('wa')}</a><div class="hours"><h2>Horário</h2><div><span>Segunda a sexta-feira</span><b>10:00–12:30 e 14:00–19:00</b></div><div><span>Sábado</span><b>10:00–15:00</b></div><div><span>Domingos e feriados</span><b>Encerrado</b></div></div><h2>Como chegar</h2><p>Peça a morada e as indicações directamente à Beatriz antes da sua visita.</p><a class="text-link" href="${wa('Olá, Beatriz! Pode indicar-me a morada e como chegar para entregar a roupa?')}">Pedir indicações de chegada ${icon('arrow')}</a>`]
];
for(const [route,title,desc,body] of subpages){fs.mkdirSync('docs/'+route,{recursive:true});fs.writeFileSync('docs/'+route+'index.html',head(title,desc,route)+`<body class="subpage">${icons}<header class="header"><div class="wrap header-inner">${brand('../')}<a class="text-link" href="../">Voltar ao início ${icon('arrow')}</a><a class="button button-dark header-cta" href="${wa(generalMessage)}">WhatsApp ${icon('wa')}</a></div></header><main class="wrap sub-content">${body}</main>${footer('../')}</body></html>`);}
fs.copyFileSync('src/beatriz.css','docs/assets/beatriz.css');
await build({entryPoints:['src/beatriz.js'],bundle:true,minify:true,format:'iife',target:['safari15','chrome100','firefox100'],outfile:'docs/assets/beatriz.js'});
fs.writeFileSync('docs/assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#cf2465"/><text x="32" y="47" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="48" fill="white">B</text></svg>');
fs.writeFileSync('docs/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${b.url}sitemap.xml\n`);
fs.writeFileSync('docs/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...subpages.map(p=>p[0])].map(route=>`<url><loc>${b.url+route}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('docs/llms.txt',`# Engomadoria Beatriz Lavandaria\n\n> Engomadoria, lavandaria para Alojamento Local e serviços de limpeza têxtil. Pedidos por WhatsApp.\n\n## Contacto\n- Telefone: ${b.displayPhone}\n- WhatsApp: https://wa.me/351923250845\n\n## Preços\n${b.packs.map(p=>`- ${p.pieces} peças: ${p.price} €`).join('\n')}\n- Roupa branca para Alojamento Local: 2 €/kg\n- Confirmar peças abrangidas, disponibilidade e prazo directamente com a Beatriz.\n\n## Horário\n- Segunda a sexta-feira: 10:00–12:30 e 14:00–19:00\n- Sábado: 10:00–15:00\n- Domingos e feriados: encerrado\n\n## Serviços\n- ${b.services.join('\n- ')}\n- Entre outros serviços de limpeza têxtil.\n\n## Páginas\n- [Packs e serviços](${b.url})\n- [Preços](${b.url}precos/)\n- [Perguntas frequentes](${b.url}perguntas-frequentes/)\n- [Contactos](${b.url}contactos/)\n\n## Limites da informação\nA morada, a localidade e o domínio próprio não estão confirmados. Não inferir localização, recolha, entrega, avaliações ou prazos. Pedir indicações directamente no WhatsApp. As imagens editoriais não representam as instalações.\n`);
console.log('Built 4 static pages, bundled Motion, sitemap and llms.txt.');
